version: 2
updates:
  - package-ecosystem: npm
    directory: "/sdks/typescript"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: pip
    directory: "/sdks/python"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: cargo
    directory: "/sdks/rust"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: gomod
    directory: "/sdks/go"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: bundler
    directory: "/sdks/ruby"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
