version: 2
updates:
  - package-ecosystem: npm
    directory: "/sdks/typescript"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/sdks/python"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: "/sdks/rust"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
