[package]
name = "bcs"
version = "0.1.3"
authors = ["Diem <opensource@diem.com>"]
description = "Binary Canonical Serialization (BCS)"
repository = "https://github.com/bcs-sdks/bcs-sdks"
homepage = "https://github.com/bcs-sdks/bcs-sdks"
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.70"

[dependencies]
thiserror = "1.0.22"
serde = { version = "1.0.117", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"
proptest-derive = "0.4"

[[bench]]
name = "bcs_bench"
harness = false
