# frozen_string_literal: true

require "rake/testtask"
require "rubocop/rake_task"

Rake::TestTask.new(:test) do |t|
  t.libs << "spec"
  t.libs << "lib"
  t.test_files = FileList["spec/**/*_spec.rb"]
end

RuboCop::RakeTask.new(:rubocop) do |task|
  task.options = ["--display-cop-names"]
end

desc "Run tests and linting"
task default: %i[test rubocop]
