disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_name
  - file_length
  - function_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_parameter_alignment_on_call

included:
  - Sources
  - Tests

excluded:
  - .build

reporter: "xcode"
